"""Modifed Test to Users | Added new table Products

Revision ID: 9dbec3a37659
Revises: 
Create Date: 2025-07-15 12:53:17.100862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbec3a37659'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_test_description'), table_name='test')
    op.drop_index(op.f('ix_test_id'), table_name='test')
    op.drop_index(op.f('ix_test_name'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    op.create_index(op.f('ix_test_name'), 'test', ['name'], unique=False)
    op.create_index(op.f('ix_test_id'), 'test', ['id'], unique=False)
    op.create_index(op.f('ix_test_description'), 'test', ['description'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
